from django.urls import path

from apps.ferramentas.views import (
        cadastro_tensao_energia,
        lista_tensao_energia,
        index_ferramentas,
        editar_tensao_energia,
        excluir_tensao_energia, 
        cadastro_modelo_sala,
        lista_modelo_sala,
        editar_modelo_sala,
        excluir_modelo_sala,
        cadastro_modelo_equipamento,
        lista_modelo_equipamento,
        editar_modelo_equipamento,
        excluir_modelo_equipamento,
        cadastro_tipo_linha,
        lista_tipo_linha,
        editar_tipo_linha,
        excluir_tipo_linha,
        cadastro_tipo_contencao,
        lista_tipo_contencao,
        editar_tipo_contencao,
        excluir_tipo_contencao,
        cadastro_tipo_gerenciamento,
        lista_tipo_gerenciamento,
        editar_tipo_gerenciamento,
        excluir_tipo_gerenciamento
        )

urlpatterns = [
        path('index_ferramentas', index_ferramentas, name='index_ferramentas'),
        path('cadastro_tensao', cadastro_tensao_energia, name='cadastro_tensao'),
        path('index_tensao', lista_tensao_energia, name='index_tensao'),
        path('editar_tensao/<int:tensao_energia_id>/', editar_tensao_energia, name='editar_tensao'),
        path('excluir_tensao/<int:tensao_energia_id>/', excluir_tensao_energia, name='excluir_tensao'),
        path('cadastro_sala', cadastro_modelo_sala, name='cadastro_sala'),
        path('index_sala', lista_modelo_sala, name='index_sala'),
        path('editar_sala/<int:modelo_sala_id>/', editar_modelo_sala, name='editar_sala'),
        path('excluir_sala/<int:modelo_sala_id>/', excluir_modelo_sala, name='excluir_sala'),
        path('cadastro_equipamento', cadastro_modelo_equipamento, name='cadastro_equipamento'),
        path('index_equipamento', lista_modelo_equipamento, name='index_equipamento'),
        path('editar_equipamento/<int:modelo_equipamento_id>/', editar_modelo_equipamento, name='editar_equipamento'),
        path('excluir_equipamento/<int:modelo_equipamento_id>/', excluir_modelo_equipamento, name='excluir_equipamento'),
        path('cadastro_linha', cadastro_tipo_linha, name='cadastro_linha'),
        path('index_linha', lista_tipo_linha, name='index_linha'),
        path('editar_linha/<int:tipo_linha_id>/', editar_tipo_linha, name='editar_linha'),
        path('excluir_linha/<int:tipo_linha_id>/', excluir_tipo_linha, name='excluir_linha'),
        path('cadastro_contencao', cadastro_tipo_contencao, name='cadastro_contencao'),
        path('index_contencao', lista_tipo_contencao, name='index_contencao'),
        path('editar_contencao/<int:tipo_contencao_id>/', editar_tipo_contencao, name='editar_contencao'),
        path('excluir_contencao/<int:tipo_contencao_id>/', excluir_tipo_contencao, name='excluir_contencao'),
        path('cadastro_gerenciamento', cadastro_tipo_gerenciamento, name='cadastro_gerenciamento'),
        path('index_gerenciamento', lista_tipo_gerenciamento, name='index_gerenciamento'),
        path('editar_gerenciamento/<int:tipo_gerenciamento_id>/', editar_tipo_gerenciamento, name='editar_gerenciamento'),
        path('excluir_gerenciamento/<int:tipo_gerenciamento_id>/', excluir_tipo_gerenciamento, name='excluir_gerenciamento'),
        
]