# Generated by Django 5.0.2 on 2024-04-17 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatistica_geral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracao', models.IntegerField(blank=True, default=0, null=True)),
                ('orcamento', models.IntegerField(blank=True, default=0, null=True)),
                ('pedido', models.IntegerField(blank=True, default=0, null=True)),
                ('variacao', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estatistica_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracao', models.IntegerField(blank=True, default=0, null=True)),
                ('orcamento', models.IntegerField(blank=True, default=0, null=True)),
                ('pedido', models.IntegerField(blank=True, default=0, null=True)),
                ('variacao', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
