# Generated by Django 5.0.2 on 2024-04-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estatistica_geral',
            old_name='variacao',
            new_name='efetivacao',
        ),
        migrations.RenameField(
            model_name='estatistica_user',
            old_name='variacao',
            new_name='efetivacao',
        ),
    ]
