# Generated by Django 5.0.2 on 2024-03-22 12:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(default=datetime.datetime.today)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('endereco_cliente', models.CharField(max_length=100)),
                ('cidade', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(default='', max_length=2)),
                ('cep', models.CharField(default='', max_length=9)),
                ('cnpj_cpf', models.CharField(default='', max_length=18)),
                ('insc_estadual', models.CharField(default='', max_length=25)),
                ('fone', models.CharField(default='', max_length=25)),
                ('email', models.CharField(default='', max_length=100)),
                ('forma_pagamento', models.CharField(choices=[('A VISTA', 'A Vista'), ('FINANCIADO', 'Financiado'), ('ENTRADA + PARCELAS', 'Entrada + parcelas')], default='', max_length=100)),
                ('pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CHEQUE', 'Cheque'), ('DEPOSITO', 'Depósito'), ('BOLETO', 'Boleto')], default='', max_length=100)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parcelas', models.CharField(default='', max_length=100)),
                ('observacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='produto.produto')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
            ],
        ),
    ]
