# Generated by Django 5.0.2 on 2024-02-23 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('data_mensagem', models.DateTimeField(default=datetime.datetime.now)),
                ('lida', models.BooleanField(default=False)),
                ('data_leitura', models.DateTimeField(blank=True)),
            ],
        ),
    ]
