# Generated by Django 5.0.2 on 2024-02-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='data_leitura',
            field=models.DateTimeField(),
        ),
    ]
