# Generated by Django 5.0.2 on 2024-02-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0002_alter_conversa_data_leitura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversa',
            name='data_leitura',
        ),
        migrations.AddField(
            model_name='conversa',
            name='autor',
            field=models.TextField(default=''),
        ),
    ]
