# Generated by Django 5.0.2 on 2024-02-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0003_remove_conversa_data_leitura_conversa_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='autor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
