# Generated by Django 5.0.2 on 2024-03-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0001_initial'),
        ('ferramentas', '0002_tipo_contencao'),
        ('produto', '0002_produto_tipo_contencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurador',
            name='tipo_contencao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferramentas.tipo_contencao'),
        ),
        migrations.CreateModel(
            name='Item_configurador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('configurador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurador.configurador')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurador', to='produto.produto')),
            ],
        ),
    ]
