# Generated by Django 5.0.2 on 2024-03-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0002_configurador_tipo_contencao_item_configurador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_configurador',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='item_configurador',
            name='valor_unitario',
        ),
    ]
