# Generated by Django 5.0.2 on 2024-03-25 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0003_remove_item_configurador_valor_total_and_more'),
        ('ferramentas', '0003_tipo_gerenciamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurador',
            name='gerenciamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configurador',
            name='tipo_gerenciamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferramentas.tipo_gerenciamento'),
        ),
    ]
