# Generated by Django 5.0.2 on 2024-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0006_item_configurador_valor_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurador',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
