# Generated by Django 5.0.2 on 2024-04-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0007_configurador_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurador',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
