# Generated by Django 5.0.2 on 2024-05-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0009_configurador_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurador',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='configurador',
            name='cnpj_cpf',
        ),
        migrations.RemoveField(
            model_name='configurador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='configurador',
            name='endereco_cliente',
        ),
        migrations.RemoveField(
            model_name='configurador',
            name='insc_estadual',
        ),
        migrations.RemoveField(
            model_name='configurador',
            name='observacao',
        ),
        migrations.AddField(
            model_name='configurador',
            name='nome_fazenda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
