# Generated by Django 5.0.2 on 2024-05-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurador', '0011_configurador_altitude_configurador_vacuo_recomendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurador',
            name='numero_conjuntos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
