# Generated by Django 5.0.2 on 2024-05-08 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0017_alter_producao1_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase_pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao_pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_situacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Envolvido_pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envolvido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='envolvido_pipeline', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historico_pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fase', models.DateField(default=django.utils.timezone.now)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_pipeline', to='pipeline.fase_pipeline')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_pipeline', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('pessoa_contato', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('setor_atividade', models.CharField(max_length=100)),
                ('fonte_lead', models.CharField(max_length=100)),
                ('detalhes_oportunidade', models.TextField()),
                ('demo_tecnica', models.BooleanField(default=False)),
                ('produto_customizado', models.TextField(blank=True, null=True)),
                ('detalhes_proposta', models.TextField(blank=True, null=True)),
                ('total_proposta', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('desconto_proposta', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('acrescimo_proposta', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('final_proposta', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('validade_proposta', models.DateField()),
                ('fase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline', to='pipeline.fase_pipeline')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline', to=settings.AUTH_USER_MODEL)),
                ('situacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline', to='pipeline.situacao_pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Itens_pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itens_pipeline', to='produto.produto')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pipeline', to='pipeline.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade_pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atividade', models.DateField(default=django.utils.timezone.now)),
                ('atividade', models.CharField(max_length=300)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividade_pipeline', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade_pipeline', to='pipeline.pipeline')),
            ],
        ),
    ]
