# Generated by Django 5.0.2 on 2024-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_envolvido_pipeline_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pipeline',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itens_pipeline',
            name='produto',
            field=models.CharField(max_length=300),
        ),
    ]
