# Generated by Django 5.0.2 on 2024-02-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(default='', max_length=100)),
                ('unidade', models.CharField(default='', max_length=4)),
                ('descricao', models.TextField()),
                ('peso', models.CharField(default='', max_length=100)),
                ('dimensoes', models.CharField(default='', max_length=100)),
                ('categoria', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
