# Generated by Django 5.0.2 on 2024-03-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_tipo_contencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='sistema_limpeza',
            field=models.BooleanField(default=False),
        ),
    ]
