# Generated by Django 5.0.2 on 2024-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_produto_tipo_gerenciamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='extracao',
            field=models.BooleanField(default=False),
        ),
    ]
