# Generated by Django 5.0.2 on 2024-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produto_extracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='conj_ordenha',
            field=models.BooleanField(default=False),
        ),
    ]
