# Generated by Django 5.0.2 on 2024-04-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_produto_nobreak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
    ]
