# Generated by Django 5.0.2 on 2024-04-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_subcategoria_options_alter_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='maximo_vacuo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
