# Generated by Django 5.0.2 on 2024-05-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_produto_maximo_vacuo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
    ]
