# Generated by Django 5.0.2 on 2024-05-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_producao1_producao2'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao1',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='producao1',
            name='nome',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Producao2',
        ),
    ]
