# Generated by Django 5.0.2 on 2024-05-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_alter_producao1_produto_producao2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao1',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='producao2',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='producao1',
            name='produto',
            field=models.ForeignKey(null=2, on_delete=django.db.models.deletion.CASCADE, related_name='producao1s', to='produto.produto'),
        ),
    ]
