# Generated by Django 5.0.2 on 2024-05-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_alter_producao1_options_alter_producao2_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao1',
            options={'ordering': ['codigo']},
        ),
    ]
