# Generated by Django 5.0.2 on 2024-05-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0016_alter_producao1_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao1',
            options={'ordering': ['nome']},
        ),
    ]
