# Generated by Django 5.0.2 on 2024-04-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_alter_orcamento_parcelas_alter_orcamento_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='vencimento_orcamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
