# Generated by Django 5.0.2 on 2024-04-16 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0005_orcamento_dias_faltantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data_orcamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
