# Generated by Django 5.0.2 on 2024-04-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0006_alter_orcamento_data_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='dias_faltantes',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
