# Generated by Django 5.0.2 on 2024-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0003_tipo_gerenciamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/excel/')),
            ],
        ),
    ]
