# Generated by Django 5.0.2 on 2024-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0004_arquivoexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_equipamento',
            name='fator_calculo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
